typography_spectrum: 0.676041713450104
color:
  brandStrength: 0.11857610521838069
  lightness: 0.11217186972498894
  saturation: 0.4100959128700197
  rhythmicContrast: 0.047582169994711876
  brandColors:
    - '#0FB6BE'
    - '#F05540'
    - '#8ACEB8'
    - '#FFFFFF'
    - '#83452F'
layout_spectrum: 0.38411103072576225
name: Overlap Interactive
navigation:
  - name: The Ars VR headset showdown-Oculus Rift vs. HTC Vive
    id: e603eb99-0edb-49bd-8467-e4ee116509ee
    type: content
title: We Are Digital Navigators
description: Marketing  |  Developing  |  Designing  |  Strategy
